name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - run: mvn -B package --file pom.xml
#    - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
#      uses: samuelmeuli/action-maven-publish@v1
#      with:
#        nexus_username: ${{ secrets.nexus_username }}
#        nexus_password: ${{ secrets.nexus_password }}
#        gpg_private_key: ${{ secrets.gpg_private_key }}
#        gpg_passphrase: ${{ secret }}
